### ISSUE TITLE
Review the target audience of the README.md file and other small changes.

### ISSUE THREAD

**Issue by marlycormar** [ctsit/send_rx#58]
The README.md file should be written with a redcap user in mind (rather than a developer). As such, please consider the following changes:
- Add a section that specifically targets the developer. In that section, include the download/installation of composer. 
- Add to documentation that UserProfile module should be activated either globally or in the three projects used to setup send_rx.
- Change Table-based authentication for any type of authentication.
- It is no longer needed to enter the project ID, as it is a dropdown menu now. Update documentation to reflect this changes.
- Please look out for any other needed changes.

**Comment by tbembersimeao** [comment]
@marlycormar thanks for your input on README, answering point by point:

> Add a section that specifically targets the developer. In that section, include the download/installation of composer.

The documentation already includes Composer download/installation instructions - I think we don't need a developer section for that, since Composer is a dependency and should be installed no matter if the end user is a developer or not

> Add to documentation that UserProfile module should be activated either globally or in the three projects used to setup send_rx.

That's actually a regression due to External Module updates - User Profile is supposed to be enabled for all projects by default, I've made a fix on [this PR](https://github.com/ctsit/redcap_user_profile/pull/7)

> - Change Table-based authentication for any type of authentication
> - It is no longer needed to enter the project ID, as it is a dropdown menu now. Update documentation to reflect this changes.
> - Please look out for any other needed changes.
Done on [this PR](https://github.com/ctsit/send_rx/pull/60)
